/** #26 Steering Rail — one intervention's alpha sweep, drawn as the grid it is.
 *
 *  `nebulai intervene` runs ONE verb (clamp / add / ablate / cap) at a grid of
 *  alpha over a set of prompts, keeping the un-hooked baseline beside every
 *  intervened run. Each column here is one (alpha, prompt) cell and its height
 *  is the real measured quantity:
 *
 *    KL( p_baseline(next token) ‖ p_intervened(next token) )  in bits
 *
 *  taken at the final position over the full 50,257-way distribution, computed
 *  in float64 by the producer. Not a similarity score and not a hand-built
 *  "steering strength" — the number that says how far the model's next-token
 *  belief actually moved.
 *
 *  THREE THINGS THIS VIEW REFUSES TO DO, each of which is why it is a bar stage
 *  and not a line chart.
 *
 *  1. **The alpha = 0 row is drawn, at zero, in its own colour.** It is the
 *     control: the producer installed no hook at all and asserted the logits
 *     were bit-identical to the baseline before it was allowed to write the
 *     file. Dropping the row because "it has no data" would delete the only
 *     row that makes the others mean anything. And it is NOT coloured as a
 *     faint measurement at the cool end of the ramp — it is the zero the ramp
 *     is measured from. If a bundle ever claims an identity row that was not
 *     identical, the view says so on the canvas rather than plotting it as a
 *     small effect.
 *  2. **No curve is drawn through the alphas.** Between 0.25 and 0.5 nothing
 *     was measured, and a line there invents a reading at every pixel. Five
 *     alphas are five columns.
 *  3. **Height and colour read the SAME normalization**, so a tall column is a
 *     bright column by construction and the two channels cannot tell different
 *     stories about one measurement.
 *
 *  The D3 claim sentence rides on the figure (not in a footer, §2.4) and is
 *  generated by the producer from the measured numbers — including when what
 *  the numbers support is "this moved the distribution and did not move the
 *  target". The generations themselves live in `chrome/SteerRail.tsx` beside
 *  the stage, because they are text and text belongs in the DOM; hovering a
 *  column drives the rail's selection so the two always describe one cell.
 *
 *  Drawn on `ChartStage` (three/webgpu + TSL + bloom). Source: intervene_*.json.
 */

import type { GpuTier } from "@psychix/viz/capabilities";
import { InterpTooltip, type TipRow } from "@psychix/viz/chart-tooltip";
import type { StatTile } from "@psychix/viz/StatStrip";
import { loadIntervene, type InterveneBundle, type InterveneRun } from "../../data/interp";
import { ChartStage, type BarData, type ChartStageLook } from "./chart-stage";
import type { InterpDriver } from "./InterpDriver";
import {
  CONTROL_RGB,
  alphaLabel,
  barHeight,
  cageHeight,
  controlStatus,
  fmtAlpha,
  maxKl as bundleMaxKl,
  norm,
  peakKl,
  publishSteer,
  ramp,
  registerSteerApply,
  shortPrompt,
  takePendingSteer,
  type SteerCell,
} from "./steer";

const CELL = 0.74;
const INSET = { left: 92, top: 40, right: 48, bottom: 104 };
const LABEL_MIN_PX = 11;

const LOOK: ChartStageLook = {
  frameColor: 0x3d4560,
  frameOpacity: 0.7,
  emissiveMin: 0.6,
  emissiveMax: 1.18,
  dimLevel: 0.24,
  azimuth: -0.68,
  elevation: 0.58,
  fov: 38,
  bloom: { strength: 0.42, radius: 0.28, threshold: 0.86 },
};

export class SteerDriver implements InterpDriver {
  readonly animated = false;
  private stage = new ChartStage(LOOK);
  private canvas!: HTMLCanvasElement;
  private tooltip!: InterpTooltip;
  private labelRoot!: HTMLElement;
  private claimRoot!: HTMLElement;

  private bundle: InterveneBundle | null = null;
  private nRow = 0; // alphas
  private nCol = 0; // prompts
  private maxKl = 0;
  private hover: SteerCell | null = null;
  private sel: SteerCell | null = null;
  private lastPointerType = "mouse";

  private bufPos = new Float32Array(0);
  private bufH = new Float32Array(0);
  private bufC = new Float32Array(0);
  private bufG = new Float32Array(0);
  private bufA = new Float32Array(0);

  private cssW = 1;
  private cssH = 1;
  private disposers: Array<() => void> = [];
  private labels: HTMLElement[] = [];

  async init(canvas: HTMLCanvasElement, tier: GpuTier, overlay: HTMLElement): Promise<void> {
    this.canvas = canvas;
    await this.stage.init(canvas, tier);
    this.stage.onCamera = () => this.positionLabels();
    this.stage.onClick = (sx, sy) => this.onClick(sx, sy);

    this.tooltip = new InterpTooltip(overlay);
    this.labelRoot = document.createElement("div");
    this.labelRoot.className = "interp-steer-labels";
    overlay.appendChild(this.labelRoot);
    this.claimRoot = document.createElement("div");
    this.claimRoot.className = "interp-steer-claim";
    overlay.appendChild(this.claimRoot);

    const onMove = (e: PointerEvent) => this.onPointerMove(e);
    const onLeave = () => this.hideTip();
    const onDown = (e: PointerEvent) => {
      this.lastPointerType = e.pointerType;
    };
    canvas.addEventListener("pointermove", onMove);
    canvas.addEventListener("pointerleave", onLeave);
    canvas.addEventListener("pointerdown", onDown);
    const unregister = registerSteerApply((sel) => this.applySelection(sel));
    this.disposers.push(() => {
      canvas.removeEventListener("pointermove", onMove);
      canvas.removeEventListener("pointerleave", onLeave);
      canvas.removeEventListener("pointerdown", onDown);
      unregister();
    });
  }

  async setModel(model: string): Promise<void> {
    const b = await loadIntervene(model);
    if (!b.rows?.length || !b.prompts?.length) {
      throw new Error("intervention sweep has no cells");
    }
    this.bundle = b;
    this.nRow = b.rows.length;
    this.nCol = b.prompts.length;
    this.maxKl = bundleMaxKl(b);

    const n = this.nRow * this.nCol;
    this.bufPos = new Float32Array(n * 2);
    this.bufH = new Float32Array(n);
    this.bufC = new Float32Array(n * 3);
    this.bufG = new Float32Array(n);
    this.bufA = new Float32Array(n);
    const hx = this.nCol / 2;
    const hz = this.nRow / 2;
    for (let r = 0; r < this.nRow; r++) {
      for (let c = 0; c < this.nCol; c++) {
        const k = r * this.nCol + c;
        // x = prompt, z = alpha. Alpha 0 sits at the far edge so the sweep
        // grows toward the viewer in the order it is read: control first.
        this.bufPos[k * 2] = c + 0.5 - hx;
        this.bufPos[k * 2 + 1] = r + 0.5 - hz;
      }
    }
    this.stage.setLattice({
      halfX: hx,
      halfZ: hz,
      cageY: cageHeight(this.nRow),
      divX: this.nCol,
      divZ: this.nRow,
    });
    this.stage.fitInset(INSET);
    this.hover = null;
    // An episode step (or a rail interaction before the canvas was up) may
    // already have named a cell; honour it. Otherwise open on the strongest
    // cell of the first prompt — the sweep's own headline.
    const want = takePendingSteer();
    this.sel = want
      ? {
          row: Math.max(0, Math.min(this.nRow - 1, want.row | 0)),
          col: Math.max(0, Math.min(this.nCol - 1, want.col | 0)),
        }
      : { row: this.nRow - 1, col: 0 };
    this.renderClaim();
    this.pushBars();
    this.positionLabels();
    publishSteer(b, this.sel);
  }

  /** Selection pushed in from the rail's slider. Clamped rather than trusted:
   *  the rail renders from the same bundle, but a stale index arriving during
   *  a model switch must land on a cell that exists. */
  private applySelection(sel: SteerCell): void {
    if (!this.bundle) return;
    const row = Math.max(0, Math.min(this.nRow - 1, sel.row | 0));
    const col = Math.max(0, Math.min(this.nCol - 1, sel.col | 0));
    if (this.sel && this.sel.row === row && this.sel.col === col) return;
    this.sel = { row, col };
    publishSteer(this.bundle, this.sel);
    this.pushBars();
    this.positionLabels();
  }

  /** Shared with `chrome/SteerRail.tsx` and with the unit tests through
   *  `./steer`, so the drawn half and the text half cannot disagree about how
   *  far a column should stand. */
  private norm(kl: number): number {
    return norm(kl, this.maxKl);
  }

  private runAt(r: number, c: number): InterveneRun | null {
    return this.bundle?.rows[r]?.runs[c] ?? null;
  }

  /** The D3 sentence, on the figure. Plus — should it ever be needed — the
   *  refusal that replaces it: a bundle whose control is not a control has no
   *  claim to make, and the only honest thing to draw is the sentence saying
   *  so. The producer refuses to write such a file, which is exactly why the
   *  view must not quietly render the row as a small effect if one appears. */
  private renderClaim(): void {
    const b = this.bundle;
    if (!this.claimRoot) return;
    this.claimRoot.textContent = "";
    if (!b) return;
    const broken = b.rows.filter((r) => r.is_identity && !r.identical_to_baseline);
    if (broken.length > 0) {
      const el = document.createElement("div");
      el.className = "interp-steer-claim-card is-broken";
      el.textContent =
        `${broken.length} control row(s) claim α = 0 but are NOT bit-identical to ` +
        `the baseline. This sweep's zero is not a zero — read no effect size from it.`;
      this.claimRoot.appendChild(el);
      return;
    }
    if (!b.claim) return;
    const el = document.createElement("div");
    el.className = "interp-steer-claim-card";
    const tag = document.createElement("span");
    tag.className = "interp-steer-claim-tag";
    tag.textContent = "claim";
    const txt = document.createElement("span");
    txt.textContent = b.claim;
    el.append(tag, txt);
    this.claimRoot.appendChild(el);
  }

  private pushBars(): void {
    const n = this.nRow * this.nCol;
    if (n === 0) return;
    const cage = cageHeight(this.nRow);
    for (let r = 0; r < this.nRow; r++) {
      const row = this.bundle?.rows[r];
      for (let c = 0; c < this.nCol; c++) {
        const k = r * this.nCol + c;
        const run = this.runAt(r, c);
        const t = this.norm(run?.kl_bits ?? 0);
        this.bufH[k] = barHeight(run?.kl_bits ?? 0, this.maxKl, this.nRow);
        this.bufG[k] = t;
        const rgb = row?.is_identity ? CONTROL_RGB : ramp(t);
        this.bufC[k * 3] = rgb[0] / 255;
        this.bufC[k * 3 + 1] = rgb[1] / 255;
        this.bufC[k * 3 + 2] = rgb[2] / 255;
        // the selected prompt's whole column of alphas stays foreground: the
        // sweep is read DOWN one prompt, so dimming its other alphas would
        // hide the comparison the view exists for
        const lit = !this.sel || this.sel.col === c;
        const hovered = this.hover?.row === r && this.hover.col === c;
        this.bufA[k] = lit || hovered ? 1 : 0;
      }
    }
    const d: BarData = {
      count: n,
      pos: this.bufPos,
      height: this.bufH,
      color: this.bufC,
      glow: this.bufG,
      active: this.bufA,
      cellX: CELL,
      cellZ: CELL,
    };
    this.stage.setBars(d);
    this.syncProbe();
    this.stage.render();
  }

  private syncProbe(): void {
    const h = this.hover ?? this.sel;
    if (!h) {
      this.stage.setProbe(null);
      return;
    }
    const run = this.runAt(h.row, h.col);
    this.stage.setProbe(
      h.col + 0.5 - this.nCol / 2,
      barHeight(run?.kl_bits ?? 0, this.maxKl, this.nRow),
      h.row + 0.5 - this.nRow / 2,
    );
  }

  // ---- labels ---------------------------------------------------------------

  private ensureLabels(n: number): void {
    while (this.labels.length < n) {
      const el = document.createElement("div");
      el.className = "interp-stage-lab";
      this.labelRoot.appendChild(el);
      this.labels.push(el);
    }
  }

  private positionLabels(): void {
    const b = this.bundle;
    if (!b || !this.labelRoot) return;
    const hx = this.nCol / 2;
    const hz = this.nRow / 2;
    const cage = cageHeight(this.nRow);

    const stride = (
      a: [number, number] | null,
      c: [number, number] | null,
      n: number,
      minPx: number,
    ) => {
      if (!a || !c) return 1;
      const gap = Math.hypot(c[0] - a[0], c[1] - a[1]);
      return gap < 0.01 ? Math.max(1, n) : Math.max(1, Math.ceil(minPx / gap));
    };
    // prompts get more room than alphas: the label is a phrase, not a number
    const colStride = stride(
      this.stage.project(0.5 - hx, 0, hz),
      this.stage.project(1.5 - hx, 0, hz),
      this.nCol,
      52,
    );
    const rowStride = stride(
      this.stage.project(-hx, 0, 0.5 - hz),
      this.stage.project(-hx, 0, 1.5 - hz),
      this.nRow,
      LABEL_MIN_PX,
    );

    type Spec = { p: [number, number] | null; text: string; cls: string };
    const specs: Spec[] = [];
    for (let c = 0; c < this.nCol; c += colStride) {
      specs.push({
        p: this.stage.project(c + 0.5 - hx, 0, hz + 0.55),
        text: shortPrompt(b.prompts[c] ?? ""),
        cls: `interp-stage-lab is-col${this.sel?.col === c ? " is-sel" : ""}`,
      });
    }
    for (let r = 0; r < this.nRow; r += rowStride) {
      const row = b.rows[r];
      specs.push({
        p: this.stage.project(-hx - 0.55, 0, r + 0.5 - hz),
        // the control says so on the axis, not only in the legend
        text: alphaLabel(row),
        cls: `interp-stage-lab is-row${this.sel?.row === r ? " is-sel" : ""}`,
      });
    }

    const post = this.stage.heightPost(-1, 1);
    if (post) {
      const cls = `interp-stage-lab ${post.side === "left" ? "is-h" : "is-hl"}`;
      // Linear ticks printed in the bundle's OWN units. Printing the numbers is
      // what stops two sweeps being compared by eye merely because their
      // tallest columns reach the same place on the screen.
      for (let i = 0; i <= 4; i++) {
        const frac = i / 4;
        specs.push({
          p: this.stage.project(post.x, frac * cage, post.z),
          text: (frac * this.maxKl).toFixed(2),
          cls,
        });
      }
      specs.push({
        p: this.stage.project(post.x, cage + 0.9, post.z),
        text: "KL bits",
        cls: "interp-stage-cap",
      });
    }
    specs.push({
      p: this.stage.project(0, 0, hz + 1.7),
      text: "prompt →",
      cls: "interp-stage-cap",
    });
    specs.push({
      p: this.stage.project(-hx - 2.3, 0, 0),
      text: "α →",
      cls: "interp-stage-cap",
    });

    this.ensureLabels(specs.length);
    for (let k = 0; k < this.labels.length; k++) {
      const el = this.labels[k]!;
      const s = specs[k];
      // Every anchor sits OUTSIDE the cage by design, so at some orbits one
      // slides past the edge — and a label clamped back inside would point at
      // something other than what it names.
      if (
        !s ||
        !s.p ||
        s.p[0] < 2 ||
        s.p[1] < 2 ||
        s.p[0] > this.cssW - 2 ||
        s.p[1] > this.cssH - 2
      ) {
        el.style.display = "none";
        continue;
      }
      el.className = s.cls;
      el.textContent = s.text;
      el.style.display = "";
      // `translate`, never `transform` — the anchoring offset lives in CSS
      // `transform` and writing both here would clobber it
      el.style.translate = `${Math.round(s.p[0])}px ${Math.round(s.p[1])}px`;
    }
  }

  // ---- interaction ----------------------------------------------------------

  private pick(sx: number, sy: number): SteerCell | null {
    const idx = this.stage.pickAt(sx, sy);
    if (idx < 0 || this.nCol === 0) return null;
    return { row: (idx / this.nCol) | 0, col: idx % this.nCol };
  }

  private onClick(sx: number, sy: number): void {
    const cell = this.pick(sx, sy);
    if (!cell) {
      this.tooltip.pinned = false;
      this.hideTip();
      return;
    }
    this.sel = cell;
    publishSteer(this.bundle, this.sel);
    this.pushBars();
    this.positionLabels();
    // touch has no hover to read the selected cell from — pin the readout open
    if (this.lastPointerType === "touch") {
      this.hover = cell;
      this.pushBars();
      this.tooltip.pinned = true;
      this.showTooltipFor(cell, sx, sy);
    }
  }

  private onPointerMove(e: PointerEvent): void {
    if (this.tooltip.pinned) return;
    if (!this.bundle) return;
    // mid-orbit the pointer is steering the camera, not reading the data
    if (this.stage.isDragging) {
      this.hideTip();
      return;
    }
    const rect = this.canvas.getBoundingClientRect();
    const sx = e.clientX - rect.left;
    const sy = e.clientY - rect.top;
    const cell = this.pick(sx, sy);
    const same = cell && this.hover && cell.row === this.hover.row && cell.col === this.hover.col;
    if (!same) {
      this.hover = cell;
      this.pushBars();
    }
    if (!cell) {
      this.hideTip();
      return;
    }
    this.showTooltipFor(cell, sx, sy);
  }

  private showTooltipFor(cell: SteerCell, sx: number, sy: number): void {
    const b = this.bundle;
    const row = b?.rows[cell.row];
    const run = this.runAt(cell.row, cell.col);
    if (!b || !row || !run) return;
    const rgb = row.is_identity ? CONTROL_RGB : ramp(this.norm(run.kl_bits));
    const rows: TipRow[] = [
      {
        kind: "label",
        text: row.is_identity
          ? "α 0 · control, no hook installed"
          : `α ${fmtAlpha(row.alpha)} · ${b.verb}`,
        swatch: [rgb[0], rgb[1], rgb[2]],
      },
      {
        text: "KL(base ‖ steered)",
        value: `${run.kl_bits.toFixed(4)} bits`,
        hot: !row.is_identity,
      },
      { text: "logits", value: run.identical ? "bit-identical" : "changed" },
      {
        text: "‖resid‖ final",
        value: `${run.resid_norm_baseline.toFixed(1)} → ${run.resid_norm_intervened.toFixed(1)}`,
      },
    ];
    // Teacher-forced target logprobs catch the effect the argmax hides — and on
    // this bundle they are the rows that say reading is not writing.
    for (const t of run.targets ?? []) {
      rows.push({
        text: `logp “${t.text.trim()}”`,
        value: `${t.baseline_logprob.toFixed(2)} → ${t.intervened_logprob.toFixed(2)}`,
      });
    }
    rows.push({ text: truncate(run.intervened.text.trim().replace(/\s+/g, " "), 96) });
    this.tooltip.show(rows);
    this.tooltip.move(sx, sy, this.cssW, this.cssH);
    this.canvas.style.cursor = "crosshair";
  }

  private hideTip(): void {
    if (this.tooltip.pinned) return;
    this.tooltip.hide();
    if (this.hover) {
      this.hover = null;
      this.pushBars();
    }
    this.canvas.style.cursor = "";
  }

  stats(): StatTile[] {
    const b = this.bundle;
    if (!b) return [];
    const ctrl = controlStatus(b);
    const peak = peakKl(b);
    return [
      { label: "verb", value: b.verb, title: b.rows[b.rows.length - 1]?.protocol ?? b.verb },
      { label: "α steps", value: String(b.rows.length) },
      { label: "prompts", value: String(b.prompts.length) },
      {
        label: "control",
        // three states, never two: an absent control and a failed one are not
        // the same thing, and neither is the case that licenses the figure
        value: ctrl === "absent" ? "—" : ctrl === "identical" ? "identical" : "BROKEN",
        title:
          ctrl === "absent"
            ? "this sweep shipped without an α = 0 row — there is no control to read against"
            : "the α = 0 row installed no hook at all; the producer asserted the " +
              "logits were bit-identical to the baseline before writing this bundle",
      },
      {
        label: "peak KL",
        value: peak === null ? "—" : `${peak.toFixed(3)} bits`,
        title:
          "largest KL(baseline ‖ intervened) over the full vocabulary at the " +
          "final position, across every (α, prompt) cell that installed a hook",
      },
    ];
  }

  frame(): void {
    // static: the stage redraws on camera change and on selection
  }

  resize(width: number, height: number, dpr: number): void {
    this.cssW = width;
    this.cssH = height;
    this.stage.resize(width, height, dpr);
    this.positionLabels();
    this.stage.render();
  }

  dispose(): void {
    for (const d of this.disposers) d();
    this.disposers = [];
    this.tooltip?.dispose();
    this.labelRoot?.remove();
    this.claimRoot?.remove();
    this.labels = [];
    publishSteer(null, null);
    this.stage.dispose();
  }
}

/** Trimmed for the tooltip's last line: the generation is the point, but a
 *  tooltip is not where a paragraph belongs — the full text is in the rail. */
function truncate(s: string, max: number): string {
  return s.length <= max ? s : `${s.slice(0, max - 1)}…`;
}
