/** The fan as GEOMETRY: what the field is allowed to draw around an ensemble.
 *
 *  The reference values in the first block are not hand-derived — they are the
 *  output of `numpy.quantile(values, q)` with its default linear method, which
 *  is exactly what `seer/ensemble.py#quantile` calls. If this module and the
 *  backend ever disagree about what p10 means, the panel's band and the field's
 *  band are two different measurements wearing one name, and these tests are
 *  the only place that would notice.
 *
 *  The rest of the file is about refusals: no box under two runs, no run
 *  extended past where it stopped, no interpolation between steps.
 */

import { describe, expect, it } from "vitest";
import {
  boxEdges,
  ENVELOPE_HI_Q,
  ENVELOPE_LO_Q,
  envelopeSteps,
  envelopeVertices,
  firstThinStep,
  medianVertices,
  MIN_RUNS_FOR_FAN,
  MIN_RUNS_PER_STEP_FOR_BOX,
  quantile,
  type RunPath,
} from "../../src/scene/sessions/envelope";

/** `[values, q, np.quantile(values, q)]` — generated by running numpy, not by
 *  reading this implementation. */
const NUMPY: [number[], number, number][] = [
  [[0, 1], 0.1, 0.1],
  [[0, 1], 0.5, 0.5],
  [[0, 1], 0.9, 0.9],
  [[0, 1, 2], 0.1, 0.2],
  [[0, 1, 2], 0.5, 1.0],
  [[0, 1, 2], 0.9, 1.8],
  [[3, 1, 2, 10], 0.1, 1.3],
  [[3, 1, 2, 10], 0.5, 2.5],
  [[3, 1, 2, 10], 0.9, 7.900000000000001],
  [[-0.5, 0.25, 0.75, 1, 2.5], 0.1, -0.19999999999999996],
  [[-0.5, 0.25, 0.75, 1, 2.5], 0.5, 0.75],
  [[-0.5, 0.25, 0.75, 1, 2.5], 0.9, 1.9000000000000001],
  [[1, 1, 1], 0.1, 1],
  [[1, 1, 1], 0.5, 1],
  [[1, 1, 1], 0.9, 1],
  [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7], 0.1, 0.16000000000000003],
  [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7], 0.5, 0.4],
  [[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7], 0.9, 0.64],
];

describe("quantile — the backend's, to the float", () => {
  for (const [vals, q, want] of NUMPY) {
    it(`q(${JSON.stringify(vals)}, ${q}) = ${want}`, () => {
      expect(quantile(vals, q)).toBeCloseTo(want, 12);
    });
  }

  it("an empty list has no quantile — NaN, never 0", () => {
    expect(Number.isNaN(quantile([], 0.5))).toBe(true);
    expect(quantile([], 0.5)).not.toBe(0);
  });

  it("one value is its own every quantile", () => {
    expect(quantile([4.25], 0.1)).toBe(4.25);
    expect(quantile([4.25], 0.5)).toBe(4.25);
    expect(quantile([4.25], 0.9)).toBe(4.25);
  });

  it("does not reorder the caller's array", () => {
    const vals = [3, 1, 2];
    quantile(vals, 0.5);
    expect(vals).toEqual([3, 1, 2]);
  });

  it("uses the quantiles the backend's fan_envelope is named after", () => {
    // seer/ensemble.py: ENVELOPE_LO_Q / ENVELOPE_HI_Q, fan_envelope "p10_p90"
    expect(ENVELOPE_LO_Q).toBe(0.1);
    expect(ENVELOPE_HI_Q).toBe(0.9);
    // seer/ensemble.py: MIN_RUNS_FOR_FAN
    expect(MIN_RUNS_FOR_FAN).toBe(3);
    expect(MIN_RUNS_PER_STEP_FOR_BOX).toBe(2);
  });
});

/** Three runs of unequal length, so every step but the first is an attrition
 *  test. x is the step, y and z are deliberately spread. */
const A: RunPath = [
  [0, 0, 0],
  [1, 10, 100],
  [2, 20, 200],
  [3, 30, 300],
];
const B: RunPath = [
  [0, 2, 0],
  [1, 12, 140],
  [2, 22, 260],
];
const C: RunPath = [
  [0, 4, 0],
  [1, 14, 180],
];

describe("envelopeSteps — only the runs that reached a step", () => {
  const steps = envelopeSteps([A, B, C]);

  it("is as long as the longest run, not as long as the shortest", () => {
    expect(steps.map((s) => s.step)).toEqual([0, 1, 2, 3]);
  });

  it("reports the n that got there, and it falls", () => {
    expect(steps.map((s) => s.n)).toEqual([3, 3, 2, 1]);
  });

  it("a run that ended is absent, not held at its last position", () => {
    // if C were extended, step 2's y quantiles would still see y = 14
    const s2 = steps[2]!;
    expect(s2.lo[1]).toBeCloseTo(quantile([20, 22], ENVELOPE_LO_Q), 12);
    expect(s2.hi[1]).toBeCloseTo(quantile([20, 22], ENVELOPE_HI_Q), 12);
    expect(s2.lo[1]).toBeGreaterThan(14);
  });

  it("takes the median per axis, the backend's way", () => {
    expect(steps[1]!.median).toEqual([
      quantile([1, 1, 1], 0.5),
      quantile([10, 12, 14], 0.5),
      quantile([100, 140, 180], 0.5),
    ]);
  });

  it("bands a step with two runs and refuses one with a single run", () => {
    expect(steps.map((s) => s.banded)).toEqual([true, true, true, false]);
  });

  it("the one-run step's box is its median, and nothing draws it", () => {
    const s3 = steps[3]!;
    expect(s3.lo).toEqual(s3.median);
    expect(s3.hi).toEqual(s3.median);
    // a zero-width box would read as three runs agreeing perfectly
    expect(envelopeVertices([s3]).length).toBe(0);
  });

  it("names the first step it could not band", () => {
    expect(firstThinStep(steps)).toBe(3);
    expect(firstThinStep(envelopeSteps([A, B]))).toBe(3);
    expect(firstThinStep(envelopeSteps([A, A, A]))).toBe(null);
  });

  it("has no steps at all with no runs", () => {
    expect(envelopeSteps([])).toEqual([]);
  });

  it("skips a hole rather than inventing a step for it", () => {
    // every run is length 2, so there is no step 2 to report an n of 0 for
    expect(envelopeSteps([C, C, C]).map((s) => s.step)).toEqual([0, 1]);
  });
});

describe("vertices — a stack of boxes, not a tube", () => {
  const steps = envelopeSteps([A, B, C]);

  it("emits 12 edges per banded step and nothing for the rest", () => {
    const v = envelopeVertices(steps);
    const banded = steps.filter((s) => s.banded).length;
    expect(banded).toBe(3);
    expect(v.length).toBe(banded * 12 * 2 * 3);
  });

  it("every vertex of a box is a corner of that box — no interpolation", () => {
    const s = steps[1]!;
    const pts: number[] = [];
    boxEdges(s, pts);
    for (let i = 0; i < pts.length; i += 3) {
      for (let c = 0; c < 3; c++) {
        const v = pts[i + c]!;
        expect(v === s.lo[c] || v === s.hi[c]).toBe(true);
      }
    }
  });

  it("draws no edge BETWEEN steps — the boxes never touch", () => {
    // an edge spanning two steps would have to leave step 1's x extent
    const s = steps[1]!;
    const pts: number[] = [];
    boxEdges(s, pts);
    for (let i = 0; i < pts.length; i += 3) {
      expect(pts[i]!).toBeGreaterThanOrEqual(s.lo[0]);
      expect(pts[i]!).toBeLessThanOrEqual(s.hi[0]);
    }
  });

  it("the median polyline joins consecutive medians, including the thin step", () => {
    const m = medianVertices(steps);
    expect(m.length).toBe((steps.length - 1) * 6);
    expect([m[0], m[1], m[2]]).toEqual(steps[0]!.median);
    expect([m[m.length - 3], m[m.length - 2], m[m.length - 1]]).toEqual(
      steps[steps.length - 1]!.median,
    );
  });

  it("one step is a point with no line to draw", () => {
    expect(medianVertices(envelopeSteps([C.slice(0, 1)])).length).toBe(0);
  });
});
